eureka:
  client:
    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
server:
  port: 10086
spring:
  application:
    name: eurekaserver
#  main:
#    allow-bean-definition-overriding: true
